apiVersion: v1
kind: Service
metadata:
  name: serviceapi-service
  labels:
    app: serviceapi-service
spec:
  selector:
    app: service-api-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
